{
 "title": "Internet Speed Test",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Download", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "value",
     "measurement": "download",
     "query": "SELECT \"value\" / 125000 FROM \"download\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "alias": "value",
     "measurement": "download",
     "query": "SELECT \"value\" / 125000 FROM \"download\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Upload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Upload",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "up",
     "measurement": "download",
     "query": "SELECT \"up\" / 125000 FROM \"download\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "up" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "alias": "up",
     "measurement": "download",
     "query": "SELECT \"up\" / 125000 FROM \"download\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "up" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "latency",
     "measurement": "download",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "latency",
     "measurement": "download",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Jitter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Jitter",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "jitter",
     "measurement": "download",
     "select": [
      [
       { "params": [ "jitter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jitter History",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "jitter",
     "measurement": "download",
     "select": [
      [
       { "params": [ "jitter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Tests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Tests",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "measurement": "download",
     "query": "SELECT \"value\" /125000 AS \"Download (Mbps)\", \"up\" /125000 AS \"Upload (Mbps)\",  \"latency\" AS \"Latency (ms)\", \"jitter\" AS \"Jitter (ms)\" FROM \"download\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "up" ], "type": "field" },
       { "params": [ "Upload" ], "type": "alias" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "jitter" ], "type": "field" },
       { "params": [ "Jitter" ], "type": "alias" }
      ],
      [
       { "params": [ "latency" ], "type": "field" },
       { "params": [ "Latency" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}