version: '3.8'
services:
  tester:
    build: ./tester
    networks: 
      - speedtest
    depends_on: 
      - influxdb
  grafana:
    image: grafana/grafana:7.4.0
    ports:
      - 3000:3000 
    networks: 
      - speedtest
    volumes:
      - ./grafana/grafana_data:/var/lib/grafana 
      - ./grafana/grafana-provisioning:/etc/grafana/provisioning
    depends_on: 
      - influxdb
  influxdb: 
      image: influxdb:1.8
      container_name: influxdb 
      ports:
        - 8086:8086 
      volumes:
        - ./influxdb/influxdb_data:/var/lib/influxdb 
      environment:
        - INFLUXDB_DB=balena 
        - INFLUXDB_ADMIN_USER=root 
        - INFLUXDB_ADMIN_PASSWORD=root 
        - INFLUXDB_HTTP_AUTH_ENABLED=false 
      networks: 
        - speedtest
networks:
  speedtest:
    driver: bridge