services:  
  mosquitto: 
    image: eclipse-mosquitto:2 
    ports:
      - 1883:1883 
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf 
      - mosquitto_data:/mosquitto/data 
      - mosquitto_log:/mosquitto/log 
  telegraf: 
    image: telegraf:1.18 
      volumes:
        - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf 
      depends_on: 
        - influxdb
influxdb: 
    image: influxdb:1.8 
    ports:
      - 8086:8086 
    volumes:
      - influxdb_data:/var/lib/influxdb 
    environment:
      - INFLUXDB_DB=iescelia_db 
      - INFLUXDB_ADMIN_USER=root 
      - INFLUXDB_ADMIN_PASSWORD=root 
      - INFLUXDB_HTTP_AUTH_ENABLED=true 