version: '3.8'
services:
  tester:
    build: ./tester
    networks: 
      - speedtest
  mosquitto: 
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883 
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf 
      - ./mosquitto/mosquitto_data:/mosquitto/data 
      - ./mosquitto/mosquitto_log:/mosquitto/log 
    networks: 
      - speedtest
  telegraf: 
    image: telegraf:1.18 
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf 
    depends_on: 
      - influxdb
    networks: 
      - speedtest
  influxdb: 
      image: influxdb:1.8
      container_name: influxdb 
      ports:
        - 8086:8086 
      volumes:
        - ./influxdb/influxdb_data:/var/lib/influxdb 
      environment:
        - INFLUXDB_DB=iescelia_db 
        - INFLUXDB_ADMIN_USER=root 
        - INFLUXDB_ADMIN_PASSWORD=root 
        - INFLUXDB_HTTP_AUTH_ENABLED=true 
      networks: 
        - speedtest
networks:
  speedtest:
    driver: bridge